all : partie1 partie2 prodcons prod cons

partie1 : partie1.c
	gcc partie1.c -o partie1

partie2 : partie2.c	
	gcc partie2.c -o partie2	

prodcons : prodcons.c
	gcc prodcons.c -o prodcons

prod : prod.c
	gcc prod.c -o prod

cons : cons.c
	gcc cons.c -o cons

clean :
	rm partie1
	rm partie2
	rm prod
	rm cons
	rm prodcons
