all : tp5_barriere_thibault.pdf

update : tp5_barriere_thibault.tex
	pdflatex tp5_barriere_thibault.tex

tp5_barriere_thibault.pdf : tp5_barriere_thibault.tex
	pdflatex tp5_barriere_thibault.tex
	pdflatex tp5_barriere_thibault.tex
