all : tp6_barriere_thibault.pdf

update : tp6_barriere_thibault.tex
	pdflatex tp6_barriere_thibault.tex

tp6_barriere_thibault.pdf : tp6_barriere_thibault.tex
	pdflatex tp6_barriere_thibault.tex
	pdflatex tp6_barriere_thibault.tex
